/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class database_Database */

#ifndef _Included_database_Database
#define _Included_database_Database
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     database_Database
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_database_Database_init(JNIEnv *, jobject);

/*
 * Class:     database_Database
 * Method:    execute
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_database_Database_execute(JNIEnv *, jobject,
                                                         jstring);

/*
 * Class:     database_Database
 * Method:    printTable
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_database_Database_printTable(JNIEnv *, jobject);

/*
 * Class:     database_Database
 * Method:    save_sql
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_database_Database_save_1sql(JNIEnv *, jobject,
                                                           jstring);

/*
 * Class:     database_Database
 * Method:    save
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_database_Database_save(JNIEnv *, jobject,
                                                      jstring);

/*
 * Class:     database_Database
 * Method:    load
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_database_Database_load(JNIEnv *, jobject,
                                                      jstring);

/*
 * Class:     database_Database
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_database_Database_close(JNIEnv *, jobject);

/*
 * Class:     database_Database
 * Method:    tableNames
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_database_Database_tableNames(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
